version: "3.8"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.5.0
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data/
    environment:
      NEO4J_AUTH: "neo4j/mypassword"
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/slim_app
    command: >
      sh -c "composer install --working-dir=/var/www/slim_app && php-fpm"
  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
